name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics with Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          token: ${{ secrets.METRICS_TOKEN }}  # or use token: NOT_NEEDED if no private info
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2024        # or 2023, etc.
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
