name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          token: NOT_NEEDED
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2024
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5

      - name: Commit and Push Updated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.plugin.skyline.svg
          git commit -m "chore: update GitHub Skyline SVG"
          git push
